spring.application.name=splitmint-backend

# Database Configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/splitmint
# spring.datasource.username=postgres
# spring.datasource.password=Gaurav@321
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.security=DEBUG

splitmint.app.jwtSecret=splitmintSecretKeyThatShouldBeLongEnoughForHS512AlgorithmExpectedToDidRequireAtLeast64Bytes
splitmint.app.jwtExpirationMs=86400000

server.port=8080
spring.profiles.active=prod



